DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    TOTAL_EMPRESTIMO DOUBLE NOT NULL,
    JUROS DOUBLE NOT NULL,
    ANOS INTEGER NOT NULL
);
